/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.edu.ifsul.lpoo_sistemaestacionamentoifsul.view;

import com.mycompany.lpoo_sistemaestacionamentoifsul.dao.PersistenciaJPA;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import static model.EntradaSaida_.veiculo;
import model.Modelo;
import model.Pessoa;
import model.TipoVeiculo;
import model.VeiOficial;
import model.Veiculo;

/**
 *
 * @author paula
 */
public class TelaCadastroVeiculo extends javax.swing.JDialog {

    private Veiculo veiculo;
    PersistenciaJPA jpa;
    /**
     * Creates new form TelaCadastroVeiculo
     */
    public TelaCadastroVeiculo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jpa = new PersistenciaJPA();
        jPanel2.setVisible(false);
        loadTipoVeiculo();
        loadPessoas();
        loadModelos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        lblTitulo = new javax.swing.JLabel();
        lblPlaca = new javax.swing.JLabel();
        lblCor = new javax.swing.JLabel();
        lblTipoVeiculo = new javax.swing.JLabel();
        lblProprietario = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        txtCor = new javax.swing.JTextField();
        cmbTipoVeiculo = new javax.swing.JComboBox<>();
        cmbProprietario = new javax.swing.JComboBox<>();
        cmbModelo = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnAddModelo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblChassi = new javax.swing.JLabel();
        txtChassi = new javax.swing.JTextField();
        lblRenavan = new javax.swing.JLabel();
        txtRenavan = new javax.swing.JTextField();
        checkOficial = new javax.swing.JCheckBox();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        lblTitulo.setText("Cadastro de Veículo");

        lblPlaca.setText("Placa:");

        lblCor.setText("Cor:");

        lblTipoVeiculo.setText("Tipo de veículo:");

        lblProprietario.setText("Proprietário:");

        lblModelo.setText("Modelo:");

        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });

        cmbTipoVeiculo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTipoVeiculoItemStateChanged(evt);
            }
        });
        cmbTipoVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoVeiculoActionPerformed(evt);
            }
        });

        cmbProprietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProprietarioActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAddModelo.setText("+");
        btnAddModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddModeloActionPerformed(evt);
            }
        });

        lblChassi.setText("Chassi:");

        lblRenavan.setText("Renavan:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblChassi)
                        .addGap(18, 18, 18)
                        .addComponent(txtChassi, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblRenavan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRenavan, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChassi)
                    .addComponent(txtChassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRenavan)
                    .addComponent(txtRenavan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        checkOficial.setText("Veículo oficial");
        checkOficial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOficialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPlaca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblCor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTipoVeiculo)
                                    .addComponent(lblModelo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cmbModelo, 0, 221, Short.MAX_VALUE)
                                    .addComponent(cmbTipoVeiculo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbProprietario, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAddModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49))
                            .addComponent(lblProprietario)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(checkOficial)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(lblTitulo)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitulo)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlaca)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCor)
                    .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoVeiculo)
                    .addComponent(cmbTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProprietario)
                    .addComponent(cmbProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelo)
                    .addComponent(cmbModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddModelo))
                .addGap(40, 40, 40)
                .addComponent(checkOficial)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            // Inicializa veículo ou veículo oficial com os dados comuns
            Veiculo veiculoBase = createVeiculoBase();

            jpa.conexaoAberta();

            if (!checkOficial.isSelected()) {
                // Salva um veículo comum
                jpa.persist(veiculoBase);
            } else {
                // Cria um VeiOficial com dados adicionais e salva
                VeiOficial veiOficial = createVeiOficial((Veiculo) veiculoBase);
                jpa.persist(veiOficial);
            }

        } catch (Exception ex) {
            Logger.getLogger(TelaCadastroVeiculo.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            jpa.fecharConexao();
            dispose();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void cmbTipoVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoVeiculoActionPerformed

    private void cmbTipoVeiculoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTipoVeiculoItemStateChanged
       
    }//GEN-LAST:event_cmbTipoVeiculoItemStateChanged

    private void btnAddModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddModeloActionPerformed
        TelaCadastroModelo telaModelo = new TelaCadastroModelo(null, rootPaneCheckingEnabled);
        telaModelo.setVisible(true);

        loadModelos();
    }//GEN-LAST:event_btnAddModeloActionPerformed

    private void checkOficialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOficialActionPerformed
        boolean ehOficial = checkOficial.isSelected();
        if (ehOficial == true) {
            jPanel2.setVisible(true);
        } else {
            jPanel2.setVisible(false);
        }
    }//GEN-LAST:event_checkOficialActionPerformed

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaActionPerformed

    private void cmbProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProprietarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProprietarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCadastroVeiculo dialog = new TelaCadastroVeiculo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void loadTipoVeiculo() {
        cmbTipoVeiculo.removeAllItems();
        for (TipoVeiculo tipo : TipoVeiculo.values()) {
            cmbTipoVeiculo.addItem(tipo);
        }
    }

    public void loadPessoas() {
        cmbProprietario.removeAllItems();
        cmbProprietario.addItem(null);
        jpa.conexaoAberta();

        for (Pessoa p : jpa.getPessoas()) {
            cmbProprietario.addItem(p);
        }

        jpa.fecharConexao();
    }

    public void loadModelos() {
        cmbModelo.removeAllItems();
        cmbModelo.addItem(null);
        jpa.conexaoAberta();

        for (Modelo p : jpa.getModelos()) {
            cmbModelo.addItem(p);
        }

        jpa.fecharConexao();
    }

    private Veiculo createVeiculoBase() throws Exception {
        // Inicializa o veículo base com dados comuns
        Veiculo veiculoBase = (veiculo == null) ? new Veiculo() : veiculo;
        try {
            boolean desvinculacao = false;
            veiculoBase.setPlaca(txtPlaca.getText());
            veiculoBase.setCor(txtCor.getText());
            veiculoBase.setTipoVeiculo((TipoVeiculo) cmbTipoVeiculo.getSelectedItem());
            // Atualiza a Pessoa já vinculada, se existir
            if (veiculoBase.getProprietario() == null && (cmbProprietario.getSelectedItem() != null && veiculoBase.getProprietario() != cmbProprietario.getSelectedItem())) {
                veiculoBase.setProprietario((Pessoa) cmbProprietario.getSelectedItem());
            } else if (veiculoBase.getProprietario() != null && cmbProprietario.getSelectedItem() == null) {
                desvinculacao = true;
                veiculoBase.setProprietario(null);

            }

            if (veiculoBase.getModelo() == null && (cmbModelo.getSelectedItem() != null && cmbModelo.getSelectedItem() != veiculoBase.getModelo())) {
                veiculoBase.setModelo((Modelo) cmbModelo.getSelectedItem());
            } else if (veiculoBase.getModelo() != null && cmbModelo.getSelectedItem() == null) {
                desvinculacao = true;
                veiculoBase.setModelo(null);
            }

            if (desvinculacao) {
                jpa.conexaoAberta();
                jpa.persist(veiculoBase);
                jpa.fecharConexao();
            }
        } catch (Exception e) {
            Logger.getLogger(TelaCadastroVeiculo.class.getName()).log(Level.SEVERE, null, e);
        } finally {
            return veiculoBase;
        }
    }

    private VeiOficial createVeiOficial(Veiculo veiculoBase) throws Exception {
        VeiOficial veiOficial = (veiculoBase instanceof VeiOficial) ? (VeiOficial) veiculoBase : new VeiOficial();

        try {
            boolean desvinculacao = false;

            // Dados comuns herdados do Veiculo base
            veiOficial.setPlaca(veiculoBase.getPlaca());
            veiOficial.setCor(veiculoBase.getCor());
            veiOficial.setTipoVeiculo(veiculoBase.getTipoVeiculo());

            // Verifica e atualiza o proprietário
            if (veiOficial.getProprietario() == null && cmbProprietario.getSelectedItem() != null) {
                veiOficial.setProprietario((Pessoa) cmbProprietario.getSelectedItem());
            } else if (veiOficial.getProprietario() != null && cmbProprietario.getSelectedItem() == null) {
                desvinculacao = true;
                veiOficial.setProprietario(null);
            } else if (veiOficial.getProprietario() != null && veiOficial.getProprietario() != cmbProprietario.getSelectedItem()) {
                veiOficial.setProprietario((Pessoa) cmbProprietario.getSelectedItem());
            }

            // Verifica e atualiza o modelo
            if (veiOficial.getModelo() == null && cmbModelo.getSelectedItem() != null) {
                veiOficial.setModelo((Modelo) cmbModelo.getSelectedItem());
            } else if (veiOficial.getModelo() != null && cmbModelo.getSelectedItem() == null) {
                desvinculacao = true;
                veiOficial.setModelo(null);
            } else if (veiOficial.getModelo() != null && veiOficial.getModelo() != cmbModelo.getSelectedItem()) {
                veiOficial.setModelo((Modelo) cmbModelo.getSelectedItem());
            }

            // Adiciona os campos específicos de VeiOficial
            veiOficial.setChassi(txtChassi.getText());
            veiOficial.setRenavan(txtRenavan.getText());

            // Persistir alterações no banco, se necessário
            if (desvinculacao) {
                jpa.conexaoAberta();
                jpa.persist(veiOficial);
                jpa.fecharConexao();
            }

        } catch (Exception e) {
            Logger.getLogger(TelaCadastroVeiculo.class.getName()).log(Level.SEVERE, null, e);
        } finally {
            return veiOficial;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddModelo;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox checkOficial;
    private javax.swing.JComboBox<Modelo> cmbModelo;
    private javax.swing.JComboBox<Pessoa> cmbProprietario;
    private javax.swing.JComboBox<TipoVeiculo> cmbTipoVeiculo;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblChassi;
    private javax.swing.JLabel lblCor;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblProprietario;
    private javax.swing.JLabel lblRenavan;
    private javax.swing.JLabel lblTipoVeiculo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtChassi;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtRenavan;
    // End of variables declaration//GEN-END:variables

    
public Veiculo getVeiculo() {
        return veiculo;
    }

    public void setVeiculo(Veiculo veiculo) {
        this.veiculo = veiculo;

//        Lógica de Negócio: uma vez criado um veículo oficial ou um veículo o tipo dele não poderá ser alterado
        checkOficial.setVisible(false);

        txtCor.setText(veiculo.getCor());
        txtPlaca.setText(veiculo.getPlaca());
        cmbTipoVeiculo.setSelectedItem(veiculo.getTipoVeiculo());
        cmbProprietario.setSelectedItem(veiculo.getProprietario());
        cmbModelo.setSelectedItem(veiculo.getModelo());

        if (veiculo instanceof VeiOficial) {
            checkOficial.setSelected(true);
            jPanel2.setVisible(true);
            VeiOficial vei = (VeiOficial) veiculo;
            txtChassi.setText(vei.getChassi());
            txtRenavan.setText(vei.getRenavan());

        }
    }
}
